project:
  type: website

website:
  favicon: logo.png
  navbar:
    left:
      - file: index.qmd
        text: "About"
      - href: resume.qmd
        text: "Resume & CV"
      # - file: blog.qmd
      #   text: "Blog"
      - file: projects.qmd
        text: "Projects"
    tools:
      - icon: github
        href: https://github.com/jimtheflash/
      - icon: linkedin
        href: https://www.linkedin.com/in/jimkloet/
      - icon: shop
        menu:
          - text: DopeGenerativeArt (Etsy)
            url: https://www.etsy.com/shop/DopeGenerativeArt
          - text: Reverb Shop
            url: https://reverb.com/shop/jims-gear-bazaar-659

format:
  html:
    css: styles.css
    link-external-newwindow: true
    page-layout: full
    theme: litera

execute:
  freeze: auto