project:
  type: website

website:
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - href: resume.qmd
        text: "Resume & Talks"
      - file: blog.qmd
        text: "Blog"
      - file: projects.qmd
        text: "Projects"

format:
  html:
    css: styles.css
    link-external-newwindow: true
    page-layout: full
    theme: litera

execute:
  freeze: auto